sudo: required

env:
  - VERSION=latest
  - VERSION=1.1.1 URL=http://xenia.sote.hu/ftp/mirrors/www.apache.org/storm/apache-storm-1.1.1/apache-storm-1.1.1.tar.gz
  - VERSION=1.1.0 URL=http://xenia.sote.hu/ftp/mirrors/www.apache.org/storm/apache-storm-1.1.0/apache-storm-1.1.0.tar.gz
  - VERSION=1.0.2 URL=http://xenia.sote.hu/ftp/mirrors/www.apache.org/storm/apache-storm-1.0.2/apache-storm-1.0.2.tar.gz
  - VERSION=1.0.3 URL=http://xenia.sote.hu/ftp/mirrors/www.apache.org/storm/apache-storm-1.0.3/apache-storm-1.0.3.tar.gz

services:
   - docker

script:
   - make build

before_deploy:
   - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
   - provider: script
     script: make deploy
